# -*- coding: utf-8 -*-
"""Esperat - Seatwork 6.1 Exploratory Data Analysis on Your Own Dataset

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sivzw2lrJpbTnyl8WKN66jJpGhh0dtvo

# Instructions:

* Choose your own dataset from public repositories.
* Link your chosen dataset in this spreadsheet: https://www.kaggle.com/datasets/henryshan/sleep-health-and-lifestyle
* Perform simple exploratory data analysis using descriptive statistics.
* Employ the same steps as done in the hands-on activity and provide your own analysis of the dataset.
* Your submission must include your GitHub folder link that includes a customized readme file, Python Notebook Files, Dataset, and a simple presentation of your findings.


# Note:

* Graphing is not required but may be done for additional points.
"""

filepath = '/Sleep, Health, and Lifestyle.csv'
import pandas as pd
import numpy as np

shl = pd.read_csv(filepath)
shl

# Display the first few rows to understand its structure
data.head()

# Compute basic descriptive statistics for the numerical columns
descriptive_stats = data.describe()

# Display the descriptive statistics
descriptive_stats