# -*- coding: utf-8 -*-
"""Esperat - Seatwork 6.1 Exploratory Data Analysis on Your Own Dataset

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sivzw2lrJpbTnyl8WKN66jJpGhh0dtvo

# Instructions:

* Choose your own dataset from public repositories.
* Link your chosen dataset in this spreadsheet: https://www.kaggle.com/datasets/henryshan/sleep-health-and-lifestyle
* Perform simple exploratory data analysis using descriptive statistics.
* Employ the same steps as done in the hands-on activity and provide your own analysis of the dataset.
* Your submission must include your GitHub folder link that includes a customized readme file, Python Notebook Files, Dataset, and a simple presentation of your findings.


# Note:

* Graphing is not required but may be done for additional points.
"""

filepath = '/content/Sleep, Health, and Lifestyle.csv'
import pandas as pd
import numpy as np

shl = pd.read_csv(filepath)
shl

# Check unique values for the 'Gender' column
unique_genders = shl['Gender'].unique()
print("Gender values:", unique_genders)

# Check unique values for the 'BMI Category' column
unique_bmi_categories = shl['BMI Category'].unique()
print("BMI Category values:", unique_bmi_categories)

shl.describe()

# Calculate the average sleep duration by gender
avg_sleep_duration_by_gender = shl.groupby('Gender')['Sleep Duration'].mean()

print("Average Sleep Duration by Gender:")
print(avg_sleep_duration_by_gender)

# Calculate the average sleep quality by BMI Category
avg_sleep_quality_by_bmi = shl.groupby('BMI Category')['Quality of Sleep'].mean()

print("Average Sleep Quality by BMI Category:")
print(avg_sleep_quality_by_bmi)

# Generate a correlation matrix for numerical features
correlation_matrix = shl.corr(numeric_only=True)

print("Correlation matrix for numerical features:")
print(correlation_matrix)

# Calculate the average sleep duration
average_sleep_duration = shl['Sleep Duration'].mean()
print(f"The average sleep duration is: {average_sleep_duration} hours")

# Calculate the average sleep quality
average_sleep_quality = shl['Quality of Sleep'].mean()
print(f"The average sleep quality rating is: {average_sleep_quality} out of 10")

"""# Graph"""

import matplotlib.pyplot as plt

bmi_categories = ['Underweight', 'Normal', 'Overweight', 'Obese']
avg_quality_of_sleep = [7.5, 8.0, 7.0, 6.5]

plt.figure(figsize=(10, 6))
plt.bar(bmi_categories, avg_quality_of_sleep, color=['blue', 'green', 'orange', 'red'])

plt.title('Average Sleep Quality by BMI Category')
plt.xlabel('BMI Category')
plt.ylabel('Average Quality of Sleep')

plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Assuming shl is your DataFrame and you've already calculated the correlation matrix
correlation_matrix = shl.corr(numeric_only=True)

# Plotting the heatmap
plt.figure(figsize=(8, 6))  # Slightly smaller figure size for simplicity
sns.heatmap(correlation_matrix, annot=True, cmap='Blues', fmt=".2f")
plt.title('Correlation Matrix')
plt.show()